"""remove default price and create roomtypeprice table

Revision ID: abd9947e5d9d
Revises: 6e6e13abf5d8
Create Date: 2026-09-25 14:40:55.414901

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'abd9947e5d9d'
down_revision: Union[str, Sequence[str], None] = '6e6e13abf5d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('room_type_prices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('room_type_id', sa.Integer(), nullable=False),
    sa.Column('occupancy', sa.Integer(), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.CheckConstraint('occupancy > 0', name='ck_occupancy_positive'),
    sa.ForeignKeyConstraint(['room_type_id'], ['room_types.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('room_type_id', 'occupancy', name='uq_price_per_occupancy')
    )
    op.drop_column('room_types', 'default_price')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('room_types', sa.Column('default_price', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False))
    op.drop_table('room_type_prices')
    # ### end Alembic commands ###
